// Videos Data

export const videoData = [
  {
    video: require('../../storage/videos/video1.mp4'),
    postProfile: require('../../storage/images/post1.jpg'),
    title: 'Ram_Charan',
    description: 'Feel the buity of nature',
    likes: '245k',
    isLike: false,
  },
  {
    video: require('../../storage/videos/video2.mp4'),
    postProfile: require('../../storage/images/post2.jpg'),
    title: 'The_Groot',
    description: "It's a tea time",
    likes: '656k',
    isLike: false,
  },
  {
    video: require('../../storage/videos/video3.mp4'),
    postProfile: require('../../storage/images/post3.jpg'),
    title: 'loverland',
    description: 'Feel the buity of nature',
    likes: '243k',
    isLike: false,
  },
  {
    video: require('../../storage/videos/video4.mp4'),
    postProfile: require('../../storage/images/post4.jpg'),
    title: 'mr. bean',
    description: 'How cute it is !!',
    likes: '876k',
    isLike: false,
  },
];

// Friends Data

export const FriendsProfileData = [
  {
    name: 'Shawarma_King',
    accountName: 'Shawarma🥐',
    profileImage: require('../../storage/images/shawarma.jpg'),
    posts: 53,
    followers: '4.1M',
    following: 20,
    follow: false,
  },
  {
    name: 'Burger_King',
    accountName: 'Burger_King🍔',
    profileImage: require('../../storage/images/burger.jpg'),
    posts: 53,
    followers: '4.1M',
    following: 20,
    follow: false,
  },
  {
    name: 'Falooda_World',
    accountName: 'Falooda',
    profileImage: require('../../storage/images/falooda.jpg'),
    posts: 513,
    followers: '6.2M',
    following: 100,
    follow: false,
  },
  {
    name: 'Briyani_World',
    accountName: 'Briyani❤️',
    profileImage: require('../../storage/images/briyani.jpg'),
    posts: 50,
    followers: '4.5K',
    following: 20,
    follow: false,
  },
  {
    name: 'Tandoori',
    accountName: 'Tandoori🍗',
    profileImage: require('../../storage/images/tandoori.jpg'),
    posts: 123,
    followers: '4.1K',
    following: 123,
    follow: false,
  },
  {
    name: 'Chicken_Rice',
    accountName: 'Chicken_Rice🍚',
    profileImage: require('../../storage/images/chicken_rice.jpg'),
    posts: 50,
    followers: '4M',
    following: 45,
    follow: false,
  },
  {
    name: 'Black_Currant',
    accountName: 'Black_Currant💜',
    profileImage: require('../../storage/images/blackcurrant.jpg'),
    posts: 523,
    followers: '4.1M',
    following: 21,
    follow: false,
  },
  {
    name: 'Rasagulla_Sweet',
    accountName: 'Rasagulla',
    profileImage: require('../../storage/images/rasagulla.jpg'),
    posts: 100,
    followers: '5.3M',
    following: 340,
    follow: false,
  },
  {
    name: 'Murukku_kadai',
    accountName: 'Murukku',
    profileImage: require('../../storage/images/murukku.jpg'),
    posts: 532,
    followers: '41K',
    following: 200,
    follow: false,
  },
  {
    name: 'Murukku_kadai',
    accountName: 'Murukku',
    profileImage: require('../../storage/images/murukku.jpg'),
    posts: 532,
    followers: '41K',
    following: 200,
    follow: false,
  },
  {
    name: 'Black_Currant',
    accountName: 'Black_Currant💜',
    profileImage: require('../../storage/images/blackcurrant.jpg'),
    posts: 523,
    followers: '4.1M',
    following: 21,
    follow: false,
  },
  {
    name: 'Briyani_World',
    accountName: 'Briyani❤️',
    profileImage: require('../../storage/images/briyani.jpg'),
    posts: 50,
    followers: '4.5K',
    following: 20,
    follow: false,
  },
  {
    name: 'Chicken_Rice',
    accountName: 'Chicken_Rice🍚',
    profileImage: require('../../storage/images/chicken_rice.jpg'),
    posts: 50,
    followers: '4M',
    following: 45,
    follow: false,
  },
];